// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcb2QlZNgTfE0N-91FxKg6Snl9baByIXQ',
    appId: '1:907873847610:web:2dbb3db6cae5ca3c73a803',
    messagingSenderId: '907873847610',
    projectId: 'chat-app-6ec9a',
    authDomain: 'chat-app-6ec9a.firebaseapp.com',
    storageBucket: 'chat-app-6ec9a.appspot.com',
    measurementId: 'G-2M091N11DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoElTYsaPjvKusbqRd1dkR5TMiMCWx3E',
    appId: '1:907873847610:android:a6926d603a60b3ed73a803',
    messagingSenderId: '907873847610',
    projectId: 'chat-app-6ec9a',
    storageBucket: 'chat-app-6ec9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsvsekit7P3y4IPZlpVnRhEsqhIPy2_MY',
    appId: '1:907873847610:ios:db38c082fddd5ae973a803',
    messagingSenderId: '907873847610',
    projectId: 'chat-app-6ec9a',
    storageBucket: 'chat-app-6ec9a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsvsekit7P3y4IPZlpVnRhEsqhIPy2_MY',
    appId: '1:907873847610:ios:db38c082fddd5ae973a803',
    messagingSenderId: '907873847610',
    projectId: 'chat-app-6ec9a',
    storageBucket: 'chat-app-6ec9a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcb2QlZNgTfE0N-91FxKg6Snl9baByIXQ',
    appId: '1:907873847610:web:f43f0c1ef88c7ad273a803',
    messagingSenderId: '907873847610',
    projectId: 'chat-app-6ec9a',
    authDomain: 'chat-app-6ec9a.firebaseapp.com',
    storageBucket: 'chat-app-6ec9a.appspot.com',
    measurementId: 'G-PMWP1329J6',
  );
}
